print('{:-^30}'.format('Exercício 22'))
nome = str(input("Digite seu nome completo: "))
nome = nome.strip()
print('\n{:=^50}\n{:^50}\n{:=^50}'.format('', 'TRANSFORMANDO:', ''))
print('Nome maiúsculo: {}'.format(nome.upper()))
print('Nome minúsculo: {}'.format(nome.lower()))
nome = nome.split()
nomes_juntos = ''.join(nome)
print('Letras (Totais): {}'.format(len(nomes_juntos)))
print('Letras (Primeiro Nome): {}'.format(len(nome[0])))
print("{:=^50}".format(''))