print('{:-^30}'.format('Exercício 26'))
frase = str(input("Digite uma frase: "))
print("\n{:=^40}\n{:^40}\n{:=^40}".format('', 'LETRA A:', ''))
frase = frase.upper()
qtd_A = frase.count('A')
primeira_vez = frase.find('A')
ultima_vez = frase.rfind('A')
print("Aparece {} vezes;\nAparece pela primeira vez na posição {};\nAparece pela ultima vez na posição {}.".format(qtd_A, primeira_vez+1, ultima_vez+1))
print("{:=^40}".format(''))